import { T_Detail } from './types';

export const DetailsMocks: T_Detail[] = [
    {   'id': 1,
        'name': 'Кронштейн подушки безопасности водителя',
        'part_number': '1456163-31-A',
        'price': '2697',
        'model_info': 'Tesla Model S рест. 2019',
        'year': '2019',
        'model': 'Model S',
        'article_number': '99458031',
        'brand': 'Tesla',
        'note': 'Кронштейн подушки безопасности водителя с электропроводкой, Tesla Model S Rest, X',
        'image': "",
    },
    {   'id': 2,
        'name': 'Накладка колесной арки задний левый',
        'part_number': '1035290-00-G',
        'price': '13485',
        'model_info': 'Tesla Model X 2019',
        'year': '2019',
        'model': 'Model X',
        'article_number': '99455421',
        'brand': 'Tesla',
        'note': 'Накладка колёсной арки, задней левой, оригинал, сломано одно крепление, Tesla Model X, XRest',
        'image': "",
    },
    {   'id': 3,
        'name': 'Подушка безопасности водителя',
        'part_number': '1023381-00-I',
        'price': '2325',
        'model_info': 'Tesla Model S 2016',
        'year': '2016',
        'model': 'Model S',
        'article_number': '9895148',
        'brand': 'Tesla',
        'note': 'Подушка безопасности водителя (под восстановление), Tesla Model S, SR, X',
        'image': "",
    },
    {   'id': 4,
        'name': 'Датчик уровня пневмоподвески',
        'part_number': '1027941-00-A',
        'price': '3441',
        'model_info': 'Tesla Model X 2019',
        'year': '2019',
        'model': 'Model X',
        'article_number': '994581',
        'brand': 'Tesla',
        'note': 'Датчик уровня пневмоподвески, передний левый, с кронштейном, Tesla Model X, S, SRest',
        'image': "",
    },
    {   'id': 5,
        'name': 'Усилитель заднего бампера',
        'part_number': '1041685-00-A',
        'price': '9765',
        'model_info': 'Tesla Model S рест. 2019',
        'year': '2019',
        'model': 'Model S',
        'article_number': '99459388',
        'brand': 'Tesla',
        'note': 'Усилитель заднего бампера, Tesla Model S, SRest, SRest 2',
        'image': "",
    },
    {   'id': 6,
        'name': 'Кронштейн крепления ручки',
        'part_number': '1008404-00-C',
        'price': '465',
        'model_info': 'Tesla Model S 2014',
        'year': '2014',
        'model': 'Model S',
        'article_number': '9878558',
        'brand': 'Tesla',
        'note': 'Кронштейн крепления ручки открытия двери внутренней задней правой Tesla Model S, Model S REST DOOR OPENER BRACKET - RIGHT REAR',
        'image': "",
    }
]